### PR TITLE
Example with memory, custom stdlib

### PR DESCRIPTION
**Pull request by makxenov**

### CODE REVIEW

**Comment by NickVolynkin** [comment]
Builds on macOS/M1:
```console
$ cmake -G "Unix Makefiles" -B ${ZKLLVM_BUILD:-build} -DCMAKE_BUILD_TYPE=Release -DCIRCUIT_ASSEMBLY_OUTPUT=TRUE .
...
$ make -C ${ZKLLVM_BUILD:-build} assigner clang -j$(nproc)
...
[100%] Linking CXX executable ../../../../bin/clang-offload-packager
[100%] Built target clang-offload-packager
[100%] Linking CXX executable ../../../../bin/clang-linker-wrapper
[100%] Built target clang-linker-wrapper
[100%] Building CXX object libs/circifier/llvm/tools/clang/tools/driver/CMakeFiles/clang.dir/driver.cpp.o
[100%] Building CXX object libs/circifier/llvm/tools/clang/tools/driver/CMakeFiles/clang.dir/cc1_main.cpp.o
[100%] Building CXX object libs/circifier/llvm/tools/clang/tools/driver/CMakeFiles/clang.dir/cc1gen_reproducer_main.cpp.o
[100%] Building CXX object libs/circifier/llvm/tools/clang/tools/driver/CMakeFiles/clang.dir/clang-driver.cpp.o
[100%] Building CXX object libs/circifier/llvm/tools/clang/tools/driver/CMakeFiles/clang.dir/cc1as_main.cpp.o
[100%] Linking CXX executable ../../../../bin/clang
[100%] Built target clang
```

**Review by nkaskov — APPROVED** [review]

**Comment by makxenov** [comment]
> ```
> $ make -C ${ZKLLVM_BUILD:-build} circuit_examples -j$(sysctl -n hw.logicalcpu)
> ...
> [100%] Built target ed25519_curve_add
> /Users/n.volynkin/workspace/github/nilfoundation/zkllvm/examples/polynomial.cpp:5:1: error: unknown type name 'consteval'; did you mean 'constexpr'?
> consteval typename pallas::base_field_type::value_type
> ^~~~~~~~~
> constexpr
> 1 error generated.
> make[3]: *** [examples/CMakeFiles/polynomial_example] Error 1
> make[2]: *** [examples/CMakeFiles/polynomial_example.dir/all] Error 2
> make[2]: *** Waiting for unfinished jobs....
> [100%] Built target balance_example
> [100%] Built target arithmetics_example
> [100%] Built target poseidon_example
> [100%] Built target sha256_example
> make[1]: *** [examples/CMakeFiles/circuit_examples.dir/rule] Error 2
> make: *** [circuit_examples] Error 2
> ```

@NickVolynkin @nkaskov @nemothenoone  this failure was caused by 4bf5d18d7df5b655e11105bd98a6a0b92e9f6e82 when the option `-std=c++20` was removed. So we should ether restore the option or rewrite the example in some other way.
